/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "friuwcoerdzgzpccijsy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaXV3Y29lcmR6Z3pwY2NpanN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTkzNzcsImV4cCI6MjA2OTI3NTM3N30.iUwlE2eL7nP9QpwGmCM0N-Qd4zMdsY4a12iVYK-cwI8"